const codesandbox = {
	base: 'vs-dark',
	inherit: true,
	rules: [
		{ token: '', foreground: 'abb2bf' },
		{ token: 'comment', foreground: '5c6370', fontStyle: 'italic' },
		{ token: 'string', foreground: '98c379' },
		{ token: 'number', foreground: 'd19a66' },
		{ token: 'keyword', foreground: 'c678dd' },
		{ token: 'operator', foreground: 'c678dd' },
		{ token: 'variable', foreground: 'e5c07b' },
		{ token: 'variable.parameter', foreground: 'e5c07b' },
		{ token: 'variable.language', foreground: 'e5c07b' },
		{ token: 'variable.other', foreground: 'abb2bf' },
		{ token: 'entity.name.class', foreground: '61afef' },
		{ token: 'support.function', foreground: '56b6c2' }
	],
	colors: {
		'editor.background': '#282c34',
		'editor.foreground': '#abb2bf',
		'editor.selectionBackground': '#3e4451',
		'editor.lineHighlightBackground': '#2c313a',
		'editorCursor.foreground': '#528bff',
		'sideBar.background': '#21252b',
		'sideBar.foreground': '#abb2bf',
		'sideBarTitle.foreground': '#ffffff',
		'sideBarSectionHeader.background': '#181b20',
		'sideBarSectionHeader.foreground': '#abb2bf',
		'tab.activeBackground': '#282c34',
		'tab.inactiveBackground': '#21252b',
		'tab.activeForeground': '#ffffff',
		'tab.inactiveForeground': '#abb2bf',
		'tab.border': '#181b20',
		'statusBar.background': '#21252b',
		'statusBar.foreground': '#abb2bf',
		'statusBar.noFolderBackground': '#21252b',
		'statusBar.noFolderForeground': '#abb2bf',
		'panel.background': '#21252b',
		'panel.foreground': '#abb2bf',
		'activityBar.background': '#181b20',
		'activityBar.foreground': '#abb2bf',
		'activityBar.activeBorder': '#528bff',
		'activityBarBadge.background': '#528bff',
		'activityBarBadge.foreground': '#ffffff',
		'badge.background': '#528bff',
		'badge.foreground': '#ffffff',
		'sideBar.border': '#181b20'
	}
};

export default codesandbox;
