import type { editor } from "monaco-editor";

const dracula: editor.IStandaloneThemeData  = {
	base: 'vs-dark',
	inherit: true,
	rules: [
		{ token: '', foreground: 'F8F8F2', background: '282A36' },
		{ token: 'invalid', foreground: 'FF5555' },
		{ token: 'emphasis', fontStyle: 'italic' },
		{ token: 'strong', fontStyle: 'bold' },
		{ token: 'variable', foreground: 'F8F8F2' },
		{ token: 'variable.predefined', foreground: 'BD93F9' },
		{ token: 'variable.parameter', foreground: '50FA7B' },
		{ token: 'constant', foreground: 'F8F8F2' },
		{ token: 'comment', foreground: '6272A4' },
		{ token: 'number', foreground: 'BD93F9' },
		{ token: 'regexp', foreground: 'F78C6C' },
		{ token: 'annotation', foreground: 'F1FA8C' },
		{ token: 'type', foreground: '8BE9FD' },
		{ token: 'delimiter', foreground: 'F8F8F2' },
		{ token: 'delimiter.html', foreground: 'F8F8F2' },
		{ token: 'delimiter.xml', foreground: 'F8F8F2' },
		{ token: 'tag', foreground: 'FF79C6' },
		{ token: 'tag.id.pug', foreground: 'FF79C6' },
		{ token: 'tag.class.pug', foreground: 'FF79C6' },
		{ token: 'meta.scss', foreground: 'F8F8F2' },
		{ token: 'meta.tag', foreground: 'FF79C6' },
		{ token: 'metatag', foreground: 'F8F8F2' },
		{ token: 'metatag.content.html', foreground: 'BD93F9' },
		{ token: 'metatag.html', foreground: 'FF79C6' },
		{ token: 'metatag.xml', foreground: 'FF79C6' },
		{ token: 'metatag.php', foreground: 'F8F8F2' },
		{ token: 'key', foreground: '8BE9FD' },
		{ token: 'string.key.json', foreground: '8BE9FD' },
		{ token: 'string.value.json', foreground: 'F1FA8C' },
		{ token: 'attribute.name', foreground: '50FA7B' },
		{ token: 'attribute.value', foreground: 'F1FA8C' },
		{ token: 'attribute.value.number', foreground: 'BD93F9' },
		{ token: 'attribute.value.unit', foreground: 'BD93F9' },
		{ token: 'attribute.value.html', foreground: 'BD93F9' },
		{ token: 'attribute.value.xml', foreground: 'BD93F9' },
		{ token: 'string', foreground: 'F1FA8C' },
		{ token: 'string.html', foreground: 'F1FA8C' },
		{ token: 'string.sql', foreground: 'F1FA8C' },
		{ token: 'string.yaml', foreground: 'F1FA8C' },
		{ token: 'keyword', foreground: '8BE9FD' },
		{ token: 'keyword.json', foreground: '8BE9FD' },
		{ token: 'keyword.flow', foreground: 'FF79C6' },
		{ token: 'keyword.flow.scss', foreground: '8BE9FD' },
		{ token: 'operator.scss', foreground: 'F8F8F2' },
		{ token: 'operator.sql', foreground: 'F8F8F2' },
		{ token: 'operator.swift', foreground: 'F8F8F2' },
		{ token: 'predefined.sql', foreground: 'F8F8F2' }
	],
	colors: {
		'editor.background': '#282A36',
		'editor.foreground': '#F8F8F2',
		'editor.selectionBackground': '#44475A',
		'editor.lineHighlightBackground': '#44475A',
		'editorCursor.foreground': '#F8F8F0',
		'editorWhitespace.foreground': '#282A36'
	}
};

export default dracula;
